### ISSUE TITLE
thinker hang out long time 

### ISSUE THREAD

**Issue by letitbezh** [Goodman-lab/DP5#51]
(base) founder@ubuntu:~/IP4$ python ../DP4-AI-master/PyDP4.py -s chloroform -w gmns -m t -f mmff IP4_.sdf NMR_folder
==========================
PyDP4 script,
integrating Tinker/MacroModel,
Gaussian/NWChem and DP4
v1.0

Copyright (c) 2015-2019 Kristaps Ermanis, Alexander Howarth, Jonathan M. Goodman
Distributed under MIT license
==========================

settings.cfg is missing!
['IP4_.sdf']
NMR_folder
NMR_path
/home/founder/IP4/NMR_folder
Current working directory: /home/founder/IP4
Initial input files: ['IP4_.sdf']
NMR file: [PosixPath('/home/founder/IP4/NMR_folder/Carbon'), PosixPath('/home/founder/IP4/NMR_folder/Proton')]
Workflow: gmns

Generating diastereomers...
Getting inchi from file  IP4_.sdf
Getting inchi from file  IP4_.sdf
Number of diastereomers to be generated: 2
Isomer 0 inchi = InChI=1S/C6H10O/c1-5-3-2-4-6(5)7/h2-3,5-7H,4H2,1H3/t5-,6-/m0/s1/f/
Isomer 1 inchi = InChI=1S/C6H10O/c1-5-3-2-4-6(5)7/h2-3,5-7H,4H2,1H3/t5-,6+/m0/s1/f/
Generated input files: ['IP4_1', 'IP4_2']

Assuming all computations are done? ...  False
Using preexisting DFT data? ...  False
Performing conformational search using Tinker

Setting up Tinker files...
Tinker input for IP4_1 prepared.
Tinker input for IP4_2 prepared.

Running Tinker...
/home/founder/DP4-AI-master/bin/scan IP4_1 0 10 20 0.00001 | tee ./IP4_1.tout

I have spent a lot of time in scan, something wrong in my environment ,what can i fix it. Thanks

**Comment by KristapsE** [comment]
Are you using command line or the GUI?

Do you have TINKER installed on your system? The workflow was not able to find settings.cfg file. Once you have installled TINKER and Gaussian or NWChem, you should modifythe settings.sample file to provide the paths to these executables, and rename the file to settings.cfg. Otherwise the workflow will be unable to find TINKER executables.

Does the IP4_1.tout contain anything or is it empty? 

Finally, how fresh is your DP4-AI download? We fixed one TINKER problem in the latest update about 2 weeks ago, so it is recommended to download it again.
