### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt4agg'

### ISSUE THREAD

**Issue by quochung2310** [Goodman-lab/DP5#67]
I am trying this command:
 `python PyDP4_GUI.py`

Then error showed:
`Traceback (most recent call last):  File "/home/duc/DP5/PyDP4_GUI.py", line 8, in <module> from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas 
ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt4agg'`
(Sorry, I don't know how to insert line break inside the block code)
Run command:
`sudo apt-get install python-matplotlib-qt4`

Resulted in error:
`E: Unable to locate package python-matplotlib-qt4`

My pc is Kubuntu 22.04
Any suggestion please?
Thank you very much!

**Comment by quochung2310** [comment]
Ok, I solved it after several steps. However, I am not sure which one is the key solution ^^

First, I tried to install PyQT4 using this method: 
[https://ubuntuhandbook.org/index.php/2020/07/install-qt4-ubuntu-20-04/](url)

Run again, but it still showed the same error

Second: Edit PyDP4_GUI.py file with text editor, then change line 8 `matplotlib.backends.backend_qt4agg ` to `matplotlib.backends.backend_qt5agg `

Then it worked ^^!

P/s: for anyone failed for other reasons (i.e. some modules not found), try to install them with command `pip install`
I wrote this line for Linux beginners like me ^^

**Comment by Jonathan-Goodman** [comment]
I think the issue here may be the version of matplotlib.

This runs fine for me with matplotlib 3.4.3
The latest version has changed:
https://matplotlib.org/stable/api/backend_qt_api.html

If you have the latest version, might try changing the import statement to:
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qtagg import NavigationToolbar2QT as NavigationToolbar

Does it fix the problem?

Jonathan


From: quochung2310 ***@***.***>
Reply to: Goodman-lab/DP5 ***@***.***>
Date: Thursday, 18 August 2022 at 05:00
To: Goodman-lab/DP5 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Goodman-lab/DP5] ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt4agg' (Issue #67)


I am trying this command:
python PyDP4_GUI.py

Then error showed:
Traceback (most recent call last): File "/home/duc/DP5/PyDP4_GUI.py", line 8, in <module> from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt4agg'

Run command:
sudo apt-get install python-matplotlib-qt4

Resulted in error:
E: Unable to locate package python-matplotlib-qt4

My pc is Kubuntu 22.04
Any suggestion please?
Thank you very much!
